sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - "12"
before_install:
  - npm i npm -g
  - npm install -g @angular/cli
install:
  - npm install
script:
  - npm test
  - npm run lint
  - npm run build
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
notifications:
  email: false
